name: radolan_to_netcdf
channels:
  - conda-forge
dependencies:
 - wradlib>=1.2.1
 - netCDF4
 - numpy
 - pytest
 - pip
 - pip:
   - git+https://github.com/cchwala/radolan_to_netcdf.git#egg=radolan_to_netcdf

